### ISSUE TITLE
header

### ISSUE THREAD

**Issue by ghost** [ldo/blendhack#2]
hi

Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?
Because '304' seems to me 3.04 but '340' is 3.40 ?

see: https://fossies.org/linux/blender/doc/blender_file_format/mystery_of_the_blend.html

**Comment by ldo** [comment]
Presumably so that the next (minor) version after 3.9 can be 3.10.

My real worry is, what happens after the last of version 9._x_? Because there is only one digit in the header for the major version number. Does version 10 become version “A”?

**Comment by ghost** [comment]
If 304 is 3.4 then what becomes 3.10? It can't be 310 because the 3rd digit is used for the value after the dot.
So 311 can't be 3.11 because 3rd digit was the value behind the dot.
I don't understand? What will they do?

 I think it's wrong: 3.4 should be 340 , 3.9 should be 390 and 3.10 should be 310
No problems here!

I think they will add a digit for 10 but imho we will never see version 10 in our lives because it goes to slowly 🤣
It took 20 years to go to 3.0!
It should be 1000 for 10.00 , 1001 for 10.10 but if they will use the silly version like they do now then 10.10 will be 1001 and nobody knows anymore what this is!!!
